### ISSUE TITLE
Does the neural network require 173GiB RAM?

### ISSUE THREAD

**Issue by teodly** [matthewmcq/upscalemp3#3]
Hello, I'm interested in audio upsampling and wanted to try it out.

Trying to run it on Linux PC. So executed `python3.11 main.py in.mp3 out.wav`. The first problem was `bad marshal data (unknown type code)` but after reading some GitHub issues it turned out that I would need to downgrade Python so I tried to workaround it by recreating the model and then loading the weights, in `predict.py` I've replaced:

`model = tf.keras.models.load_model(model_filepath, custom_objects=custom_objects, safe_mode=False)`

with:

```
model = UResNet()
model.load_weights('ResUNet_LSTM_small3GB/model.weights.h5')
```

and unpacked the `.keras` file. Unfortunately it fails in `UResNet()`:

```
2024-10-04 15:56:15.145745: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 186120320000 exceeds 10% of free system memory.
2024-10-04 15:56:15.145809: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at stateless_random_ops_v2.cc:64 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[65600,709300] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "/dockerx/upscalemp3/main.py", line 64, in <module>
    mags, phases = predict.polyfit_and_predict(combined_mp3, MODEL_FILEPATH)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dockerx/upscalemp3/predict.py", line 222, in polyfit_and_predict
    pred = model_predict(harmonic_mp3, model_filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dockerx/upscalemp3/predict.py", line 204, in model_predict
    model = UResNet()
            ^^^^^^^^^
  File "/dockerx/upscalemp3/model_uresnet.py", line 120, in UResNet
    x_mag_lstm = process_with_lstm(x_mag)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dockerx/upscalemp3/model_uresnet.py", line 100, in process_with_lstm
    x = tf.keras.layers.LSTM(height * width, return_sequences=True)(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keras/src/layers/rnn/base_rnn.py", line 556, in __call__
    return super().__call__(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.11/site-packages/keras/src/backend.py", line 2100, in random_uniform
    return tf.random.stateless_uniform(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.ResourceExhaustedError: {{function_node __wrapped__StatelessRandomUniformV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} OOM when allocating tensor with shape[65600,709300] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:StatelessRandomUniformV2] name: 
```

Does the LSTM really require that much RAM or is it a bug?

**Comment by matthewmcq** [comment]
Hi @teodly 

Sorry for taking so long to get back -- there's a much better version of the model available here: [https://github.com/matthewmcq/upscalemp3_v2](https://github.com/matthewmcq/upscalemp3_v2)

The weights for which can be found linked in the readme and on the sidebar. This one should only require ~130MB of RAM. Hope this helps!
